### PR TITLE
fix other-wrappers

### PR DESCRIPTION
**Pull request by see--**
Is this the correct fix?

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks a lot! These benchmarks are not updated for a long time. I should update them to use latest tensorpack.

**Comment by see--** [comment]
Thank you! Do you have a rough estimate about how important NCHW is? I sometimes read it is not but these benchmark show otherwise.

**Comment by ppwwyyxx** [comment]
It depends on many factors. Usually it is quite important on pre-volta GPUs.

**Comment by ppwwyyxx** [comment]
Benchmarks in `other-wrappers` are rerun with TF1.13, cuda10, latest tensorpack. Most numbers improved and the gap between tensorpack and other wrappers is still large.

**Pull request merged**
